# WebP Safe Migrator - Docker Compose Override Configuration
# This file allows customization without modifying the main docker-compose.yml
# Copy this to docker-compose.override.yml and modify as needed

version: '3.8'

services:
  wordpress:
    # Uncomment to specify WordPress version
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     WORDPRESS_VERSION: "6.4"
    
    environment:
      # Custom domain configuration
      # CUSTOM_DOMAIN: "webp-migrator.local"
      
      # SSL configuration
      # ENABLE_SSL: "true"
      
      # WordPress version (if using official image instead of custom build)
      # WORDPRESS_VERSION: "6.4"
      
      # Additional WordPress configuration
      # WORDPRESS_CONFIG_EXTRA: |
      #   define('WP_DEBUG', false);
      #   define('WEBP_MIGRATOR_LOG_LEVEL', 'info');
    
    # Uncomment to use different ports (useful if 80/443 are occupied)
    # ports:
    #   - "8080:80"
    #   - "8443:443"
    
    # Additional volume mounts
    # volumes:
    #   - ./custom-themes:/var/www/html/wp-content/themes/custom:Z
    #   - ./custom-plugins:/var/www/html/wp-content/plugins/custom:Z

  db:
    # Uncomment to specify MySQL version
    # image: docker.io/library/mysql:8.0
    
    environment:
      # Custom database configuration
      # MYSQL_DATABASE: "custom_wp_db"
      # MYSQL_USER: "custom_user"
      # MYSQL_PASSWORD: "custom_password"
      # MYSQL_ROOT_PASSWORD: "custom_root_password"
    
    # Uncomment to use different port
    # ports:
    #   - "3307:3306"

  # Uncomment to add additional services
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - wordpress
