version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: webp-migrator-wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress123
      WORDPRESS_DB_NAME: wordpress_webp_test
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        define('SCRIPT_DEBUG', true);
        define('WP_MEMORY_LIMIT', '512M');
        define('FS_METHOD', 'direct');
    volumes:
      - wordpress_data:/var/www/html
      - ../src:/var/www/html/wp-content/plugins/webp-safe-migrator
      - ./uploads:/var/www/html/wp-content/uploads
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: webp-migrator-mysql
    environment:
      MYSQL_DATABASE: wordpress_webp_test
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: webp-migrator-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root123
      PMA_ARBITRARY: 1
    depends_on:
      - db
    restart: unless-stopped

  wpcli:
    image: wordpress:cli
    container_name: webp-migrator-wpcli
    volumes:
      - wordpress_data:/var/www/html
      - ../src:/var/www/html/wp-content/plugins/webp-safe-migrator
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress123
      WORDPRESS_DB_NAME: wordpress_webp_test
    depends_on:
      - db
      - wordpress
    command: tail -f /dev/null  # Keep container running
    restart: unless-stopped

volumes:
  wordpress_data:
  db_data:
